import React, { useState } from 'react';
import Layout from '../components/Layout';

const MOCK_ALERTS = [
  {
    id: 'alt-101',
    type: 'Spike Anomaly',
    severity: 'high',
    title: 'Demand Spike: BEVERAGES (Store #1)',
    msg: 'Current predicted demand is 42% above standard baseline averages. Shelf out risk is critical.',
    timestamp: '10 mins ago',
    store_nbr: 1,
    family: 'BEVERAGES',
    impact: '+42%',
    advice: [
      '🚚 Logistics: Speed up incoming distributor shipments by requesting express transit.',
      '📦 Stocking: Increase safety stock limits in the warehouse by 2.5x standard deviations.',
      '🏷️ Pricing: Disable active clearance promotions to throttle demand velocity.'
    ]
  },
  {
    id: 'alt-102',
    type: 'Drop Anomaly',
    severity: 'low',
    title: 'Demand Drop: BREAD/BAKERY (Store #3)',
    msg: 'Daily predicted demand fell 35% below seasonal averages. High inventory shrinkage risk.',
    timestamp: '1 hour ago',
    store_nbr: 3,
    family: 'BREAD/BAKERY',
    impact: '-35%',
    advice: [
      '🍞 Production: Restrict the morning bake-off schedule by 30% to prevent end-of-day waste.',
      '🛒 Merchandising: Introduce cross-merchandising discounts with hot deli beverages.',
      '📉 Purchasing: Delay raw ingredient flour orders by 48 hours.'
    ]
  },
  {
    id: 'alt-103',
    type: 'Promotion Opportunity',
    severity: 'medium',
    title: 'High Promo Sensitivity: CLEANING (Store #4)',
    msg: 'Cleaning category is showing a +28.5% promo uplift potential due to local holiday seasonality.',
    timestamp: '4 hours ago',
    store_nbr: 4,
    family: 'CLEANING',
    impact: '+28.5%',
    advice: [
      '🎯 Marketing: Launch a weekend bundling promo (buy-one-get-one 50% off).',
      '🏬 Display: Move multi-surface disinfectants to the front end-cap display racks.',
      '📦 Supply Chain: Ensure local warehouse transfers arrive before Friday morning.'
    ]
  },
  {
    id: 'alt-104',
    type: 'Spike Anomaly',
    severity: 'high',
    title: 'Demand Spike: PRODUCE (Store #12)',
    msg: 'Seasonal avocado and citrus predictions surged 52% above baseline averages.',
    timestamp: '1 day ago',
    store_nbr: 12,
    family: 'PRODUCE',
    impact: '+52%',
    advice: [
      '🚚 Procurement: Purchase directly from local growers to offset supply chain lag.',
      '❄️ Storage: Maximize cooling capacity zones to keep freshness logs high.',
      '💼 Staffing: Allocate 2 extra floor staff to fresh section stocking.'
    ]
  },
  {
    id: 'alt-105',
    type: 'Drop Anomaly',
    severity: 'low',
    title: 'Demand Drop: PERSONAL CARE (Store #19)',
    msg: 'Cold weather fluctuations have caused a 22% demand contraction in standard personal hygiene lines.',
    timestamp: '2 days ago',
    store_nbr: 19,
    family: 'PERSONAL CARE',
    impact: '-22%',
    advice: [
      '📦 Storage: Relocate slow-moving hygiene products to backend racks.',
      '📉 Ordering: Adjust replenishment automation thresholds down by 15%.'
    ]
  }
];

export default function Alerts() {
  const [filter, setFilter] = useState('all');
  const [selectedAlert, setSelectedAlert] = useState(MOCK_ALERTS[0]);

  const filteredAlerts = MOCK_ALERTS.filter(alert => {
    if (filter === 'all') return true;
    return alert.severity === filter;
  });

  const getSeverityStyle = (severity) => {
    return {
      high: { color: '#ef4444', bg: 'rgba(239,68,68,0.08)', border: 'rgba(239,68,68,0.18)', label: 'High Priority' },
      medium: { color: '#f59e0b', bg: 'rgba(245,158,11,0.08)', border: 'rgba(245,158,11,0.18)', label: 'Medium' },
      low: { color: '#3b82f6', bg: 'rgba(59,130,246,0.08)', border: 'rgba(59,130,246,0.18)', label: 'Low Priority' }
    }[severity];
  };

  return (
    <Layout activeNav="Alerts">
      <div style={{ flex: 1, overflowY: 'auto', padding: '36px 30px', animation: 'fadeUp 0.5s ease' }}>
        
        {/* Header */}
        <div style={{ marginBottom: '32px' }}>
          <h1 style={{ fontSize: '24px', fontWeight: 800, letterSpacing: '-0.8px', margin: '0 0 6px 0' }}>Logistical Alerts & Anomalies</h1>
          <p style={{ fontSize: '13.5px', color: 'rgba(255,255,255,0.4)', margin: 0 }}>
            Real-time anomaly warnings generated by backend forecasts. Click alerts to view mitigation workflows.
          </p>
        </div>

        {/* Filter Toolbar */}
        <div style={{ display: 'flex', gap: '8px', marginBottom: '24px', borderBottom: '1px solid rgba(255,255,255,0.06)', paddingBottom: '16px' }}>
          {[
            { label: 'All Alerts', value: 'all' },
            { label: '🔴 High Priority', value: 'high' },
            { label: '🟡 Medium Priority', value: 'medium' },
            { label: '🔵 Low Priority', value: 'low' }
          ].map(btn => (
            <button key={btn.value} onClick={() => setFilter(btn.value)}
              style={{
                background: filter === btn.value ? 'rgba(255,255,255,0.06)' : 'transparent',
                border: `1px solid ${filter === btn.value ? 'rgba(255,255,255,0.15)' : 'transparent'}`,
                color: filter === btn.value ? '#fff' : 'rgba(255,255,255,0.4)',
                padding: '8px 16px', borderRadius: '8px', fontSize: '13px', cursor: 'pointer', fontFamily: 'inherit', transition: 'all 0.2s'
              }}>
              {btn.label}
            </button>
          ))}
        </div>

        {/* Workspace Split Layout */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '28px', alignItems: 'start' }}>
          
          {/* Feed List */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            <div style={{ fontSize: '11px', color: 'rgba(255,255,255,0.25)', textTransform: 'uppercase', letterSpacing: '0.8px', marginBottom: '4px' }}>
              Active Incidents ({filteredAlerts.length})
            </div>

            {filteredAlerts.length === 0 ? (
              <div style={{ border: '1px solid rgba(255,255,255,0.06)', borderRadius: '12px', padding: '40px', textAlign: 'center', color: 'rgba(255,255,255,0.3)' }}>
                No active anomalies matching filter categories.
              </div>
            ) : (
              filteredAlerts.map(alert => {
                const isSelected = selectedAlert?.id === alert.id;
                const sev = getSeverityStyle(alert.severity);
                return (
                  <div key={alert.id} onClick={() => setSelectedAlert(alert)}
                    style={{
                      background: isSelected ? 'rgba(255,255,255,0.03)' : 'rgba(255,255,255,0.01)',
                      border: `1px solid ${isSelected ? 'rgba(255,255,255,0.12)' : 'rgba(255,255,255,0.06)'}`,
                      borderRadius: '12px', padding: '16px', cursor: 'pointer', transition: 'all 0.15s',
                      transform: isSelected ? 'translateX(2px)' : 'translateX(0)'
                    }}
                    onMouseEnter={e => { if(!isSelected) e.currentTarget.style.borderColor = 'rgba(255,255,255,0.1)'; }}
                    onMouseLeave={e => { if(!isSelected) e.currentTarget.style.borderColor = 'rgba(255,255,255,0.06)'; }}
                  >
                    <div style={{ display: 'flex', justifySelf: 'stretch', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '8px' }}>
                      <span style={{ fontSize: '11px', color: sev.color, background: sev.bg, border: `1px solid ${sev.border}`, padding: '2px 8px', borderRadius: '4px', fontWeight: 600 }}>
                        {sev.label}
                      </span>
                      <span style={{ fontSize: '11px', color: 'rgba(255,255,255,0.25)' }}>{alert.timestamp}</span>
                    </div>

                    <h4 style={{ fontSize: '14px', fontWeight: 700, color: '#fff', margin: '0 0 6px 0' }}>{alert.title}</h4>
                    <p style={{ fontSize: '12.5px', color: 'rgba(255,255,255,0.45)', margin: 0, lineHeight: 1.5, display: '-webkit-box', WebkitLineClamp: 2, WebkitBoxOrient: 'vertical', overflow: 'hidden' }}>
                      {alert.msg}
                    </p>
                  </div>
                );
              })
            )}
          </div>

          {/* Action Center Detail Panel */}
          {selectedAlert && (
            <div style={{ background: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: '16px', padding: '28px', position: 'sticky', top: '20px' }}>
              <div style={{ display: 'flex', justifySelf: 'stretch', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
                <span style={{ fontSize: '11px', color: 'rgba(255,255,255,0.3)', textTransform: 'uppercase', letterSpacing: '1px' }}>
                  Anomalous Incident Details
                </span>
                <span style={{ fontSize: '11px', color: 'rgba(255,255,255,0.3)' }}>ID: {selectedAlert.id}</span>
              </div>

              <h2 style={{ fontSize: '20px', fontWeight: 800, color: '#fff', margin: '0 0 10px 0', letterSpacing: '-0.5px' }}>{selectedAlert.title}</h2>
              
              <div style={{ display: 'flex', gap: '8px', marginBottom: '20px' }}>
                <span style={{ fontSize: '12px', background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '100px', padding: '4px 12px', color: 'rgba(255,255,255,0.6)' }}>
                  Store #{selectedAlert.store_nbr}
                </span>
                <span style={{ fontSize: '12px', background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '100px', padding: '4px 12px', color: 'rgba(255,255,255,0.6)' }}>
                  Family: {selectedAlert.family}
                </span>
                <span style={{ fontSize: '12px', background: selectedAlert.severity === 'high' ? 'rgba(239,68,68,0.1)' : 'rgba(34,197,94,0.1)', borderRadius: '100px', padding: '4px 12px', color: selectedAlert.severity === 'high' ? '#ef4444' : '#22c55e', fontWeight: 600 }}>
                  Impact: {selectedAlert.impact}
                </span>
              </div>

              <div style={{ borderTop: '1px solid rgba(255,255,255,0.06)', borderBottom: '1px solid rgba(255,255,255,0.06)', padding: '16px 0', marginBottom: '20px' }}>
                <p style={{ fontSize: '13px', color: 'rgba(255,255,255,0.5)', lineHeight: 1.6, margin: 0 }}>
                  {selectedAlert.msg}
                </p>
              </div>

              <h3 style={{ fontSize: '12px', color: 'rgba(255,255,255,0.3)', textTransform: 'uppercase', letterSpacing: '0.8px', margin: '0 0 14px 0' }}>
                🛡️ AI-Recommended Mitigation Plan
              </h3>
              
              <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                {selectedAlert.advice.map((item, idx) => (
                  <div key={idx} style={{ display: 'flex', gap: '10px', alignItems: 'flex-start', background: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.04)', padding: '12px 14px', borderRadius: '8px' }}>
                    <span style={{ fontSize: '12.5px', color: 'rgba(255,255,255,0.65)', lineHeight: 1.6 }}>{item}</span>
                  </div>
                ))}
              </div>

              {/* Action Button */}
              <button onClick={() => alert(`Mitigation action initiated for incident ${selectedAlert.id}`)}
                style={{ width: '100%', background: '#fff', color: '#000', border: 'none', padding: '12px', borderRadius: '8px', fontSize: '13.5px', fontWeight: 700, cursor: 'pointer', fontFamily: 'inherit', marginTop: '24px', transition: 'all 0.2s' }}
                onMouseEnter={e => e.currentTarget.style.background = 'rgba(255,255,255,0.85)'}
                onMouseLeave={e => e.currentTarget.style.background = '#fff'}>
                ⚡ Approve Mitigation Workflow
              </button>
            </div>
          )}

        </div>

      </div>
    </Layout>
  );
}
